### ISSUE TITLE
SMARTCONTRACT: Create contract interface

### ISSUE THREAD

**Issue by sergejparity** [sergejparity/voteabout#3]
Create smart contract interface with functions signatures.

```cairo
#[starknet::interface]
pub trait IVoteAbout<TContractState> {
    fn ...
}
```

**Comment by Lukman-01** [comment]
I will like to do this. I will define define all necessary interfaces.

**Comment by Deusvult6764** [comment]
I will like to work on the Interface

**Comment by sergejparity** [comment]
Let's split. This one will go to @Deusvult6764 . Of course you can cooperate and keep in touch.

**Comment by Deusvult6764** [comment]
Sure thing! we'll work together.
